services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5071:5071"
    environment:
      # ASP.NET environment
      - ASPNETCORE_ENVIRONMENT=Development

      # Connection string
      - ConnectionStrings__DevelopmentConnection=Host=postgres;Port=5432;Database=InvenireServerDatabase;Username=postgres;Password=postgres

      # JWT
      - Jwt__Issuer=Invenire
      - Jwt__SigningKey=9qiRkZxY0AwS37DQNzCHt4tRXUy5mgj7x2tNnp5bA8GSL22v4A
      - Jwt__ExpirationTime=3000000

      # SMTP
      - SMTP__Host=smtp.ethereal.email
      - SMTP__Port=587
      - SMTP__Username=alia.stehr@ethereal.email
      - SMTP__Password=1YMqYWqBXxDdsEdWKC

      # Frontend
      - Frontend__BaseAddress=http://127.0.0.1:5170
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./logs:/app/logs
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: InvenireServerDatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
